
drop schema PUBLIC cascade;

create table student(
    id bigint, -- 主键
    code varchar(50), -- 学号
    name varchar(50), -- 姓名
    sex integer, -- 性别
    age integer, -- 年龄
    political varchar(50), -- 政治面貌
    origin varchar(50), -- 籍贯
    professional varchar(50) -- 所属系
);
alter table student
    add constraint pk_student primary key (id);
alter table student
    alter column id bigint generated by default as identity (start with 1, increment by 1);


---------------------------------------------------------------------
---------------------------------------------------------------------
insert into student(id,code,name,sex,age,political,origin,professional)
    values(1,'2002015','张光和',1,21,'团员','湖北省','物流工程学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(2,'2002002','张值强',1,22,'党员','河南省','动力工程系');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(3,'2002003','槐  心',1,23,'团员','四川省','管理学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(4,'2002004','王小勇',1,23,'团员','重庆市','材料学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(5,'2002005','王历历',1,22,'党员','河北省','文法学院系');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(6,'2002006','吴孟达',1,23,'群众','香港特别行政区','计算机学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(7,'2002007','金嫣红',2,22,'团员','山西省','计算机学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(8,'2002008','刘长艳',2,22,'党员','北京市','数理学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(9,'2002009','许  强',2,23,'团员','安徽省','机械学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(10,'2002010','杨小鹃',2,20,'团员','广西','文法学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(11,'2002011','岳不群',1,25,'党员','安徽省','体育系');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(12,'2002012','任我行',1,26,'团员','江苏省','机械学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(13,'2002016','刘  渠',1,24,'团员','黑龙江省','环境工程系');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(14,'2002014','黄  蓉',2,21,'党员','福建省','外语系');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(15,'2002001','王雨嫣',2,20,'群众','浙江省','计算机学院');
insert into student(id,code,name,sex,age,political,origin,professional)
    values(16,'2002013','乔  风',1,26,'群众','青海省','继续教育学院');


commit;

shutdown;

